Vidly/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class ApplicationDbContext : DbContext
    {
        public DbSet<Mover> Movers { get; set; }
    }
}

Vidly/Models/Mover.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Mover
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Address { get; set; }
        public DateTime? PostedOn { get; set; }
    }
}

Vidly/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Vidly/Models/NotificationService.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;
using Vidly.Hubs;

namespace Vidly.Models
{
    public static class NotificationService
    {
        static readonly string conStr = ConfigurationManager.ConnectionStrings["ApplicationDbContext"].ConnectionString;

        internal static SqlCommand command = null;
        internal static SqlDependency dependency = null;

        public static string GetNotification()
        {
            try
            {
                var movers = new List<Mover>();

                using (var connection = new SqlConnection(conStr))
                {
                    connection.Open();

                    using (command = new SqlCommand(@"SELECT [Id], [Name], [PostedOn] FROM [dbo].[Movers]", connection))
                    {
                        command.Notification = null;

                        if (dependency == null)
                        {
                            dependency = new SqlDependency(command);
                            dependency.OnChange += new OnChangeEventHandler(dependency_OnChange);
                        }

                        if (connection.State == System.Data.ConnectionState.Closed)
                            connection.Open();

                        var reader = command.ExecuteReader();

                        while (reader.Read())
                        {
                            movers.Add(item: new Mover
                            {
                                Id = (int)reader["Id"],
                                Name = reader["Name"] != DBNull.Value ? (string)reader["Name"] : "",
                                PostedOn = reader["PostedOn"] != DBNull.Value ? (DateTime)reader["PostedOn"] : DateTime.Now
                            });
                        }
                    }
                }

                var jsonSerializer = new JavaScriptSerializer();

                var json = jsonSerializer.Serialize(movers);

                return json;
            }
            catch (Exception ex)
            {
                return ex.ToString();
            }
        }

        private static void dependency_OnChange(object sender, SqlNotificationEventArgs e)
        {
            if (dependency != null)
            {
                dependency.OnChange -= dependency_OnChange;
                dependency = null;

            }

            if (e.Type == SqlNotificationType.Change)
            {
                NotificationHub.Send();
            }
        }
    }
}

Vidly/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Hubs;

namespace Vidly.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public JsonResult GetNotificationContacts()
        {
            var notificationRegisterTime = Session["LastUpdated"] != null ? Convert.ToDateTime(Session["LastUpdated"]) : DateTime.Now;

            NotificationComponents nc = new NotificationComponents();

            var list = nc.GetMovers(notificationRegisterTime);

            Session["LastUpdate"] = DateTime.Now;

            return new JsonResult
            {
                Data = list,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
    }
}

Vidly/Controllers/MoversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;

namespace Vidly.Controllers
{
    public class MoversController : Controller
    {
        private ApplicationDbContext _context;
        
        public MoversController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult NewMover()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Mover mover)
        {
            if (!ModelState.IsValid)
            {
                return View("NewMover");
            }

            mover.PostedOn = DateTime.Now;
            _context.Movers.Add(mover);
            _context.SaveChanges();

            TempData["success"] = "Mover added successfully !";

            return RedirectToAction("NewMover");
        }
        // GET: Movers
        public ActionResult Index()
        {
            return View();
        }
    }
}

Vidly/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;

namespace Vidly.Controllers
{
    public class MoviesController : Controller
    {
        // GET: Movies/Random
        public ActionResult Random()
        {
            var movie = new Movie()
            {
                Name = "Shrek!"
            };

            return RedirectToAction("Index", "Home", new { page = 1, sortBy = "Name" });
        
        }

        public ActionResult ByReleaseDate(int year, int month)
        {
            return Content(year + "/" + month);
        }
    }
}

Vidly/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;

namespace Vidly.Controllers
{
    public class NotificationController : Controller
    {
        // GET: Notification
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetNotification()
        {
            return Json(NotificationService.GetNotification(), JsonRequestBehavior.AllowGet);
        }
    }
}

Vidly/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Vidly/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vidly/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Vidly/Views/Movers/NewMover.cshtml
@model Vidly.Models.Mover
@{
    ViewBag.Title = "NewMover";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var message = TempData["success"] ?? string.Empty;
}

<h2>New Mover</h2>

@if (TempData["success"] != null)
{
    <div class="alert alert-success">
        <strong>Success!</strong> @TempData["success"]
    </div>
}

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            <li>
                <strong>  @Html.ValidationMessageFor(m => m.Name) </strong>
            </li>
            <li>
                <strong>  @Html.ValidationMessageFor(m => m.Address) </strong>
            </li>
        </ul>
    </div>
}





@using (Html.BeginForm("Create", "Movers"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Address)
        @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-success">Save</button>
}

Vidly/Views/Movies/Random.cshtml
@model Vidly.Models.Movie
@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>

Vidly/Views/Notification/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div class="notification-icon" style="margin-top:10px">
    <span class="glyphicon glyphicon-envelope " style="font-size:25px"></span>
    <span class="badge" id="ntCnt"></span>
</div>

<div id="divNotificaion">

</div>


@section scripts{



    @Scripts.Render("~/Scripts/jquery.signalR-2.2.2.min.js")

    <script src="~/signalr/Hubs/"></script>

}

<script>
    $(document).ready(function () {
      //  debugger
        // Proxy created on the fly
        var hub = $.connection.notificationHub;


        // Declare a function on the hub hub so the server can invoke it
        hub.client.displayStatus = function () {
          //  debugger
            getData();
        };

        // Start the connection
        $.connection.hub.start();
        getData();

        function getData() {
            var divNotificaion = $('#divNotificaion');
            $.ajax({
                url: '/Notification/GetNotification',
                type: 'GET',
                datatype: 'json',
                success: function (data) {
                    debugger
                    data = $.parseJSON(data);
                    if (data.length > 0) {
                        divNotificaion.empty();
                        //// set Count
                        $('#ntCnt').text(data.length);

                        ///Make notification html
                        for (var i = 0; i < data.length; i++) {
                            var notification = '<div class="alert alert-danger alert-dismissable">' +
                        '<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>'
                        + data[i].Id + " " + data[i].Name + " posted on: " + data[i].PostedOn
                    '</div>'
                            divNotificaion.append(notification);
                        }

                    }
                }, error: function (r, e, w) {
                }
            });
        }
    })
</script>

Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <span class="noti glyphicon glyphicon-bell">
                    <span class="badge badge-notify" id="ntCnt"></span>
                </span>
                    
                <div class="notif-top-arrow"></div>
                <ul id="notiContent">
                </ul>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Movers", "NewMover", "Movers")</li>
                    <li>@Html.ActionLink("Notifications", "Index", "Notification")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <style type="text/css">
        /*Added css for design notification area, you can design by your self*/
        /* COPY css content from youtube video description*/

        .badge-notify {
            background: red;
            position: relative;
            top: -15px;
            left: -30px;
        }

        .noti-content {
            position: fixed;
            right: 100px;
            background: #e5e5e5;
            border-radius: 4px;
            top: 47px;
            width: 250px;
            display: none;
            border: 1px solid #9E988B;
        }

        ul#notiContent {
            max-height: 200px;
            overflow: auto;
            padding: 0px;
            margin: 0px;
            padding-left: 20px;
        }

            ul#notiContent li {
                margin: 3px;
                padding: 6px;
                background: #fff;
            }

        .noti-top-arrow {
            border-color: transparent;
            border-bottom-color: #F5DEB3;
            border-style: dashed dashed solid;
            border-width: 0 8.5px 8.5px;
            position: absolute;
            right: 32px;
            top: -8px;
        }

        span.noti {
            color: #3B5998;
            margin: 15px;
            position: fixed;
            right: 100px;
            font-size: 25px;
            cursor: pointer;
        }

        span.count {
            position: relative;
            top: -3px;
        }
    </style>

    <script type="text/javascript">
        $(function () {
            // Click on notification icon for show notification
            $('span.noti').click(function (e) {
                console.log("Bell is clicked")
                e.stopPropagation();
                $('.noti-content').show();
                var count = 0;
                count = parseInt($('span.count').html()) || 0;
                //only load notification if not already loaded
                if (count > 0) {
                    updateNotification();
                }
                $('span.count', this).html('&nbsp;');
            })
            // hide notifications
            $('html').click(function () {
                $('.noti-content').hide();
            })
            // update notification 
            function updateNotification() {
                $('#notiContent').empty();
                $('#notiContent').append($('<li>Loading...</li>'));

                $.ajax({
                    type: 'GET',
                    url: '/Notification/GetNotifications',
                    success: function (response) {
                        console.log("I am in..")
                        $('#notiContent').empty();
                        if (response.length == 0) {
                            $('#notiContent').append($('<li>No data available</li>'));
                        }
                        $.each(response, function (index, value) {
                            $('#notiContent').append($('<li>New contact : ' + value.Id + ' (' + value.Name + ') added</li>'));
                        });
                    },
                    error: function (error) {
                        console.log(error);
                    }
                })
            }
            // update notification count
            function updateNotificationCount() {
                var count = 0;
                count = parseInt($('span.count').html()) || 0;
                count++;
                $('span.count').html(count);
            }
            // signalr js code for start hub and send receive notification
            var notificationHub = $.connection.notificationHub;
            $.connection.hub.start().done(function () {
                console.log('Notification hub started');
            });

            //signalr method for push server message to client
            notificationHub.client.notify = function (message) {
                if (message && message.toLowerCase() == "added") {
                    updateNotificationCount();
                }
            }

        })
    </script>

   

</body>
</html>